cloud:
  aws:
    region:
      static: ap-northeast-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAQNTLX6QSAQDK2OOB
      secretKey: 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

application:
  bucket:
    name: test-rules-hust-bk

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error